# Generated by Django 3.0.3 on 2020-05-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200501_1013'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='nopicture.jpeg', upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('1', 'Sport'), ('2', 'Tech'), ('3', 'Health')], default='Sport', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
    ]
