# Generated by Django 3.0.3 on 2020-05-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
