# Generated by Django 3.0.3 on 2020-05-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
