# Generated by Django 3.0.3 on 2020-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200512_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
