# Generated by Django 3.0.3 on 2020-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200512_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='nopicture.jpeg', upload_to='media/productsphotos'),
        ),
    ]
