# Generated by Django 3.0.3 on 2020-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20200514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='nopicture.jpeg', upload_to='productsphotos'),
        ),
    ]
