# Generated by Django 3.0.3 on 2020-05-18 23:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shoplist',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
