# Generated by Django 3.0.3 on 2020-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='nopicture.jpeg', upload_to=''),
        ),
    ]
