# Generated by Django 3.0.3 on 2020-05-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200501_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='nopicture.jpeg', upload_to='profilepicture'),
        ),
    ]
