# Generated by Django 3.0.3 on 2020-06-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200530_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'order'), ('2', 'sell'), ('3', 'other')], default='other', max_length=50),
        ),
    ]
